name: S3 Copy

on:
  workflow_dispatch
  # push:
  #   branches:
  #     - main 
  
env:
  BUCKET: airflow
  S3_PATH: dags
  SOURCE_PATH: ./dags

jobs:
  copy_s3_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy folder from local to S3
        run: |
          aws s3 cp $SOURCE_PATH s3://$BUCKET/$S3_PATH --recursive
